# Generated by Django 5.1.2 on 2024-11-14 21:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imovel', models.CharField(choices=[('CAS', 'Casa'), ('APT', 'Apartamento'), ('LOJ', 'Loja'), ('SAL', 'Sala'), ('TER', 'Terreno')], default='CAS', max_length=3)),
                ('identificador', models.CharField(max_length=10, unique=True)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('preco_aluguel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('destaque', models.BooleanField(default=False)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('iptu', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True)),
                ('taxa_incendio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True)),
                ('condominio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True)),
                ('outras_taxas', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.inquilino')),
            ],
        ),
    ]
